services:
#    petrepatrasc_symfony_certification_understanding_authentication.example:
#        class: petrepatrasc\SymfonyCertification\UnderstandingAuthenticationBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    petrepatrasc.auth.oauth_listener:
        class: petrepatrasc\SymfonyCertification\UnderstandingAuthenticationBundle\Listener\CustomOauthListener
